#ifndef PORTENVREQS
#define PORTENVREQS

#define LATEST_TCC_VERSION 0.9.26
#define LATEST_ZSH_VERSION 5.0.2
#define LATEST_BASH_VERSION 4.2
#define LATEST_NANO_VERSION 2.3.2
#define LATEST_COREUTILS_VERSION 8.21  
#define LATEST_TMUX_VERSION 1.8

#define LATEST_GIT_VERSION 1.8.4.rc4
#define LATEST_MERCURIAL_VERSION 2.7
#define LATEST_SUBVERSION_VERSION 1.8.1
#define LATEST_BAZAAR_VERSION 2.6.0

#endif

